name: clang-tidy

on: [push, pull_request]

jobs:
  clang-tidy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install clang-tidy
      run: sudo apt-get install -y clang-tidy

    - name: Configure project with CMake
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON ..

    - name: Run clang-tidy
      run: |
        cd build
        find ../src -name '*.cpp' | xargs clang-tidy -p .
